spring:

  jpa:
#    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  mail:
    protocol: smtp
    host: smtp.timeweb.ru
    port: 465
    username: ${POST_USER}
    password: ${POST_PASS}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            protocols: TLSv1.2

server:
  port: 8080

logging:
  level:
    root: INFO