spring:

  jpa:
#    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/arrow_db
    username: main_user
    password: user666
  mail:
    protocol: smtp
    host: smtp.timeweb.ru
    port: 465
    username: service@strelaperm.ru
    password: 313Lv661q
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            protocols: TLSv1.2

server:
  port: 8080

logging:
  level:
    root: INFO